### Decision Tree

> classification algorithm....

> Its follows tree like structure to predict theo/p

<img src="https://miro.medium.com/v2/resize:fit:1430/1*rSQIIAboJftqAv_BReNipg.png">

In [47]:
import pandas as pd
import numpy as np

In [48]:
df = pd.read_excel("/content/tennis_anyone_1000.xlsx")

In [49]:
df.head()

  Day ID   Outlook Temperature Humidity    Wind Play Tennis
0  Day_1  Overcast        Cool   Normal  Strong         Yes
1  Day_2      Rain        Mild     High    Weak         Yes
2  Day_3  Overcast         Hot   Normal    Weak         Yes
3  Day_4     Sunny        Mild   Normal  Strong         Yes
4  Day_5     Sunny        Mild     High    Weak          No

In [50]:
df.columns

Index(['Day ID', 'Outlook', 'Temperature', 'Humidity', 'Wind', 'Play Tennis'], dtype='object')

In [51]:
df.drop(columns = "Day ID",inplace=True)

In [52]:
df.nunique()

Outlook        3
Temperature    3
Humidity       2
Wind           2
Play Tennis    2
dtype: int64

In [53]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Outlook']=le.fit_transform(df['Outlook']) #overcast -0,rain -1,sunny -2
df['Temperature']=le.fit_transform(df['Temperature']) #cool -0,mild-2,hot -1`
df['Humidity']=le.fit_transform(df['Humidity']) #normal -1,high =0
df['Wind']=le.fit_transform(df['Wind']) #strong -0,weak -1
df['Play Tennis']=le.fit_transform(df['Play Tennis']) #yes =1, no -1

In [54]:
df.head()

   Outlook  Temperature  Humidity  Wind  Play Tennis
0        0            0         1     0            1
1        1            2         0     1            1
2        0            1         1     1            1
3        2            2         1     0            1
4        2            2         0     1            0

In [55]:
### renaming the columns
df.rename(columns={'Play Tennis':'PlayTennis'},inplace =True)

In [56]:
df['PlayTennis'].value_counts()

PlayTennis
1    651
0    349
Name: count, dtype: int64

In [57]:
df.shape

(1000, 5)

In [58]:
###### splitting dataset vertically (input /output)
X = df.iloc[:,0:-1]
Y = df.iloc[:,-1]

In [59]:
###### splitting dataset horizontally(train and test set(20%))
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=1)

In [60]:
#### using decision Tree model
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt

DecisionTreeClassifier()

In [71]:
#### training the model
dt.fit(X_train, Y_train)

DecisionTreeClassifier()

In [72]:
#### predict

predict = dt.predict(X_test)

In [73]:
### evaluating model
from  sklearn.metrics import classification_report

print(classification_report(Y_test,predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        69
           1       1.00      1.00      1.00       131

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200

>>> Decision Tree accuracy with 100%